/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LootRouteImport } from './routes/loot'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpellsIndexRouteImport } from './routes/spells/index'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as DungeonsIndexRouteImport } from './routes/dungeons/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as DungeonsPrepareRouteImport } from './routes/dungeons/prepare'
import { Route as DungeonsIdRouteImport } from './routes/dungeons/$id'
import { Route as CharactersCharacterIdRouteImport } from './routes/characters/$character-id'
import { Route as BattleIdRouteImport } from './routes/battle/$id'
import { Route as DungeonsCompanyIdRouteImport } from './routes/dungeons/company.$id'
import { Route as BattleFinishedIdRouteImport } from './routes/battle/finished.$id'

const LootRoute = LootRouteImport.update({
  id: '/loot',
  path: '/loot',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpellsIndexRoute = SpellsIndexRouteImport.update({
  id: '/spells/',
  path: '/spells/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const DungeonsIndexRoute = DungeonsIndexRouteImport.update({
  id: '/dungeons/',
  path: '/dungeons/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const DungeonsPrepareRoute = DungeonsPrepareRouteImport.update({
  id: '/dungeons/prepare',
  path: '/dungeons/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const DungeonsIdRoute = DungeonsIdRouteImport.update({
  id: '/dungeons/$id',
  path: '/dungeons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersCharacterIdRoute = CharactersCharacterIdRouteImport.update({
  id: '/characters/$character-id',
  path: '/characters/$character-id',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleIdRoute = BattleIdRouteImport.update({
  id: '/battle/$id',
  path: '/battle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DungeonsCompanyIdRoute = DungeonsCompanyIdRouteImport.update({
  id: '/dungeons/company/$id',
  path: '/dungeons/company/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleFinishedIdRoute = BattleFinishedIdRouteImport.update({
  id: '/battle/finished/$id',
  path: '/battle/finished/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/friends': typeof FriendsRoute
  '/invitations': typeof InvitationsRoute
  '/loot': typeof LootRoute
  '/battle/$id': typeof BattleIdRoute
  '/characters/$character-id': typeof CharactersCharacterIdRoute
  '/dungeons/$id': typeof DungeonsIdRoute
  '/dungeons/prepare': typeof DungeonsPrepareRoute
  '/characters/': typeof CharactersIndexRoute
  '/dungeons/': typeof DungeonsIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/spells/': typeof SpellsIndexRoute
  '/battle/finished/$id': typeof BattleFinishedIdRoute
  '/dungeons/company/$id': typeof DungeonsCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/friends': typeof FriendsRoute
  '/invitations': typeof InvitationsRoute
  '/loot': typeof LootRoute
  '/battle/$id': typeof BattleIdRoute
  '/characters/$character-id': typeof CharactersCharacterIdRoute
  '/dungeons/$id': typeof DungeonsIdRoute
  '/dungeons/prepare': typeof DungeonsPrepareRoute
  '/characters': typeof CharactersIndexRoute
  '/dungeons': typeof DungeonsIndexRoute
  '/items': typeof ItemsIndexRoute
  '/spells': typeof SpellsIndexRoute
  '/battle/finished/$id': typeof BattleFinishedIdRoute
  '/dungeons/company/$id': typeof DungeonsCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/friends': typeof FriendsRoute
  '/invitations': typeof InvitationsRoute
  '/loot': typeof LootRoute
  '/battle/$id': typeof BattleIdRoute
  '/characters/$character-id': typeof CharactersCharacterIdRoute
  '/dungeons/$id': typeof DungeonsIdRoute
  '/dungeons/prepare': typeof DungeonsPrepareRoute
  '/characters/': typeof CharactersIndexRoute
  '/dungeons/': typeof DungeonsIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/spells/': typeof SpellsIndexRoute
  '/battle/finished/$id': typeof BattleFinishedIdRoute
  '/dungeons/company/$id': typeof DungeonsCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/friends'
    | '/invitations'
    | '/loot'
    | '/battle/$id'
    | '/characters/$character-id'
    | '/dungeons/$id'
    | '/dungeons/prepare'
    | '/characters/'
    | '/dungeons/'
    | '/items/'
    | '/spells/'
    | '/battle/finished/$id'
    | '/dungeons/company/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/friends'
    | '/invitations'
    | '/loot'
    | '/battle/$id'
    | '/characters/$character-id'
    | '/dungeons/$id'
    | '/dungeons/prepare'
    | '/characters'
    | '/dungeons'
    | '/items'
    | '/spells'
    | '/battle/finished/$id'
    | '/dungeons/company/$id'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/friends'
    | '/invitations'
    | '/loot'
    | '/battle/$id'
    | '/characters/$character-id'
    | '/dungeons/$id'
    | '/dungeons/prepare'
    | '/characters/'
    | '/dungeons/'
    | '/items/'
    | '/spells/'
    | '/battle/finished/$id'
    | '/dungeons/company/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  FriendsRoute: typeof FriendsRoute
  InvitationsRoute: typeof InvitationsRoute
  LootRoute: typeof LootRoute
  BattleIdRoute: typeof BattleIdRoute
  CharactersCharacterIdRoute: typeof CharactersCharacterIdRoute
  DungeonsIdRoute: typeof DungeonsIdRoute
  DungeonsPrepareRoute: typeof DungeonsPrepareRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  DungeonsIndexRoute: typeof DungeonsIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  SpellsIndexRoute: typeof SpellsIndexRoute
  BattleFinishedIdRoute: typeof BattleFinishedIdRoute
  DungeonsCompanyIdRoute: typeof DungeonsCompanyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loot': {
      id: '/loot'
      path: '/loot'
      fullPath: '/loot'
      preLoaderRoute: typeof LootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spells/': {
      id: '/spells/'
      path: '/spells'
      fullPath: '/spells/'
      preLoaderRoute: typeof SpellsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dungeons/': {
      id: '/dungeons/'
      path: '/dungeons'
      fullPath: '/dungeons/'
      preLoaderRoute: typeof DungeonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dungeons/prepare': {
      id: '/dungeons/prepare'
      path: '/dungeons/prepare'
      fullPath: '/dungeons/prepare'
      preLoaderRoute: typeof DungeonsPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dungeons/$id': {
      id: '/dungeons/$id'
      path: '/dungeons/$id'
      fullPath: '/dungeons/$id'
      preLoaderRoute: typeof DungeonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$character-id': {
      id: '/characters/$character-id'
      path: '/characters/$character-id'
      fullPath: '/characters/$character-id'
      preLoaderRoute: typeof CharactersCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/$id': {
      id: '/battle/$id'
      path: '/battle/$id'
      fullPath: '/battle/$id'
      preLoaderRoute: typeof BattleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dungeons/company/$id': {
      id: '/dungeons/company/$id'
      path: '/dungeons/company/$id'
      fullPath: '/dungeons/company/$id'
      preLoaderRoute: typeof DungeonsCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/finished/$id': {
      id: '/battle/finished/$id'
      path: '/battle/finished/$id'
      fullPath: '/battle/finished/$id'
      preLoaderRoute: typeof BattleFinishedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  FriendsRoute: FriendsRoute,
  InvitationsRoute: InvitationsRoute,
  LootRoute: LootRoute,
  BattleIdRoute: BattleIdRoute,
  CharactersCharacterIdRoute: CharactersCharacterIdRoute,
  DungeonsIdRoute: DungeonsIdRoute,
  DungeonsPrepareRoute: DungeonsPrepareRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  DungeonsIndexRoute: DungeonsIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  SpellsIndexRoute: SpellsIndexRoute,
  BattleFinishedIdRoute: BattleFinishedIdRoute,
  DungeonsCompanyIdRoute: DungeonsCompanyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
