/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DungeonsIndexRouteImport } from './routes/dungeons/index'
import { Route as DungeonsIdRouteImport } from './routes/dungeons/$id'
import { Route as BattleIdRouteImport } from './routes/battle/$id'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DungeonsIndexRoute = DungeonsIndexRouteImport.update({
  id: '/dungeons/',
  path: '/dungeons/',
  getParentRoute: () => rootRouteImport,
} as any)
const DungeonsIdRoute = DungeonsIdRouteImport.update({
  id: '/dungeons/$id',
  path: '/dungeons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleIdRoute = BattleIdRouteImport.update({
  id: '/battle/$id',
  path: '/battle/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/battle/$id': typeof BattleIdRoute
  '/dungeons/$id': typeof DungeonsIdRoute
  '/dungeons': typeof DungeonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/battle/$id': typeof BattleIdRoute
  '/dungeons/$id': typeof DungeonsIdRoute
  '/dungeons': typeof DungeonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/battle/$id': typeof BattleIdRoute
  '/dungeons/$id': typeof DungeonsIdRoute
  '/dungeons/': typeof DungeonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/battle/$id' | '/dungeons/$id' | '/dungeons'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/battle/$id' | '/dungeons/$id' | '/dungeons'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/battle/$id'
    | '/dungeons/$id'
    | '/dungeons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BattleIdRoute: typeof BattleIdRoute
  DungeonsIdRoute: typeof DungeonsIdRoute
  DungeonsIndexRoute: typeof DungeonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dungeons/': {
      id: '/dungeons/'
      path: '/dungeons'
      fullPath: '/dungeons'
      preLoaderRoute: typeof DungeonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dungeons/$id': {
      id: '/dungeons/$id'
      path: '/dungeons/$id'
      fullPath: '/dungeons/$id'
      preLoaderRoute: typeof DungeonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/$id': {
      id: '/battle/$id'
      path: '/battle/$id'
      fullPath: '/battle/$id'
      preLoaderRoute: typeof BattleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BattleIdRoute: BattleIdRoute,
  DungeonsIdRoute: DungeonsIdRoute,
  DungeonsIndexRoute: DungeonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
