/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as DungeonsIndexImport } from './routes/dungeons/index'
import { Route as DungeonsIdImport } from './routes/dungeons/$id'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DungeonsIndexRoute = DungeonsIndexImport.update({
  id: '/dungeons/',
  path: '/dungeons/',
  getParentRoute: () => rootRoute,
} as any)

const DungeonsIdRoute = DungeonsIdImport.update({
  id: '/dungeons/$id',
  path: '/dungeons/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/dungeons/$id': {
      id: '/dungeons/$id'
      path: '/dungeons/$id'
      fullPath: '/dungeons/$id'
      preLoaderRoute: typeof DungeonsIdImport
      parentRoute: typeof rootRoute
    }
    '/dungeons/': {
      id: '/dungeons/'
      path: '/dungeons'
      fullPath: '/dungeons'
      preLoaderRoute: typeof DungeonsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dungeons/$id': typeof DungeonsIdRoute
  '/dungeons': typeof DungeonsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dungeons/$id': typeof DungeonsIdRoute
  '/dungeons': typeof DungeonsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dungeons/$id': typeof DungeonsIdRoute
  '/dungeons/': typeof DungeonsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/dungeons/$id' | '/dungeons'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/dungeons/$id' | '/dungeons'
  id: '__root__' | '/' | '/about' | '/dungeons/$id' | '/dungeons/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DungeonsIdRoute: typeof DungeonsIdRoute
  DungeonsIndexRoute: typeof DungeonsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DungeonsIdRoute: DungeonsIdRoute,
  DungeonsIndexRoute: DungeonsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/dungeons/$id",
        "/dungeons/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/dungeons/$id": {
      "filePath": "dungeons/$id.tsx"
    },
    "/dungeons/": {
      "filePath": "dungeons/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
