import { z } from "zod";

export const SpellTypeSchema = z.union([
  z.literal("basic-attack"),
  z.literal("fireball"),
  z.literal("single-heal"),
  z.literal("crude-strike"),
  z.literal("festering-blow"),
  z.literal("cinder-wisp"),
  z.literal("vital-strike"),
  z.literal("splinter-shot"),
  z.literal("cinderbrand"),
  z.literal("precise-thrust"),
  z.literal("soulflare"),
  z.literal("charred-chains"),
  z.literal("crushing-blow"),
  z.literal("stone-bark"),
  z.literal("rootgrasp"),
  z.literal("verdant-smite"),
  z.literal("natures-embrace"),
  z.literal("lightning-surge"),
  z.literal("stunning-strike"),
  z.literal("staggering-jab"),
  z.literal("battle-roar"),
  z.literal("torrent-spiral"),
  z.literal("tidepiercer-thrust"),
  z.literal("ocean-blessing"),
  z.literal("aqua-wave"),
  z.literal("tidal-pulse"),
  z.literal("stream-of-life"),
  z.literal("rupture"),
  z.literal("storm-pulse"),
  z.literal("volt-lash"),
  z.literal("final-verdict"),
  z.literal("aegis-wall"),
  z.literal("bulwark-bash"),
  z.literal("earthshatter"),
  z.literal("deflecting-stance"),
  z.literal("bladestorm-rhythm"),
  z.literal("iron-will"),
  z.literal("arcane-channeling"),
  z.literal("fleetfoot-gambit"),
]);
export type SpellType = z.infer<typeof SpellTypeSchema>;
