import type { TieredEquipmentType } from "../items/equipment/tiered-equipment";

/** Individual v3 review; values remain authored in TIERED_EQUIPMENT. */
export const tieredEquipmentRationales = {
  "apprentice-pendant":
    "Retain the 100-Might amulet anchor: +3 INT improves eligible scaling and derived recovery. Maximum mana is unchanged. Fresh 128 paired slot trials on caster builds: mean damage change 0, remaining-HP change 0, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "emberheart-amulet":
    "Retain 220: +6 STR/+4 physical penetration give the amulet slot a physical specialization. Eligible multi-hit spells use penetration repeatedly; no magical-penetration benefit is assumed. Fresh 128 paired slot trials on physical builds: mean damage change 52.91, remaining-HP change 0.73, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "lifewell-talisman":
    "Retain 560: +12 VIT/+10 MR/+4 health recovery provide sustained wounded-tank value. VIT affects regeneration and scaling, not the persisted HP pool; mixed-pressure trials support survival without adding nominal healing twice. Fresh 128 paired slot trials on tank builds: mean damage change 48.74, remaining-HP change 116.91, deaths 32 → 26. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "moonwell-pendant":
    "Retain 310: +8 INT/+3 mana recovery support repeated spells. Paired depleted/full resource cases support the sustained-casting premium and reveal unused mana limits. Fresh 128 paired slot trials on caster builds: mean damage change 90.38, remaining-HP change 0.44, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "storm-eye-amulet":
    "Retain 430: +12 AGI and ten percentage points of crit improve compatible agility and critical builds. Extra damage is useful only before death/overkill; initiative is conditional. Fresh 128 paired slot trials on agility builds: mean damage change 108.88, remaining-HP change -5.75, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "thornwood-charm":
    "Retain 160: +4 INT/+1 flat mana recovery form a modest sustained-casting step. Paired resource-depleted cases convert some additional recovery into actions; no value for idle mana. Fresh 128 paired slot trials on caster builds: mean damage change 44.31, remaining-HP change 0.09, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "astral-regalia":
    "Retain 430: +20 INT/+18 MR/+4 mana regeneration sustain caster rotations, but give no physical armor. Slot trials confirm more spent mana and useful output; unspent recovery receives no extra value. Fresh 256 paired slot trials on caster/tank builds: mean damage change 122.67, remaining-HP change 27.45, deaths 124 → 112. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "citadel-carapace":
    "Retain 310: +26 armor/+14 MR produce strong sustained prevention, with −1 movement. Its numerical defenses are discounted for approach turns; movement-only pairs retain that cost separately from the whole-item outcome. Fresh 256 paired slot trials on agility/tank builds: mean damage change 52.54, remaining-HP change 129.06, deaths 128 → 32. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "dawnwarden-aegis":
    "Retain 560: +38 armor/+26 MR/+10 VIT, without a movement penalty, materially changes survival under mixed pressure. VIT adds regeneration and scaling, not maximum HP. Large flat defenses saturate against weak hits. Fresh 128 paired slot trials on tank builds: mean damage change 59.09, remaining-HP change 432.16, deaths 32 → 0. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "runebound-vestments":
    "Retain 220: +12 INT and +10 MR support magical offense and defense, giving no physical armor. Paired caster/tank comparisons retain matchup dependence instead of summing unlike stats. Fresh 256 paired slot trials on caster/tank builds: mean damage change 42.68, remaining-HP change -5.39, deaths 124 → 124. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "archmages-sash":
    "Retain 430: +10 INT/+10 VIT/+3 mana recovery support spell use and health recovery. Only spent mana and useful regeneration count, with fixed maximum resource pools. Fresh 256 paired slot trials on caster/tank builds: mean damage change 42.41, remaining-HP change 11.46, deaths 133 → 128. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "champions-girdle":
    "Retain 310: +8 STR/+6 VIT support sustained physical output and wounded recovery. Higher stats alone earn no triggered-effect premium. Fresh 256 paired slot trials on physical/tank builds: mean damage change 24.7, remaining-HP change 4.61, deaths 133 → 131. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "raiders-belt":
    "Retain 160: +4 STR/+3 VIT add modest physical scaling while retaining Rope Girdle recovery. Paired gains are limited by action count and missing health. Fresh 256 paired slot trials on physical/tank builds: mean damage change 9.01, remaining-HP change 0.49, deaths 133 → 132. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "rootbound-cinch":
    "Retain 220: +6 VIT/+4 armor support tank scaling, recovery and physical prevention. Slot trials cover caster-independent tank usefulness; no HP-pool bonus is assigned. Fresh 128 paired slot trials on tank builds: mean damage change 9.8, remaining-HP change 30.14, deaths 37 → 32. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "rope-girdle":
    "Retain the 100-Might belt anchor: +3 VIT affects regeneration and VIT-based skills, not maximum health. Current tactical regeneration uses 0.375 × VIT before rounding. Fresh 128 paired slot trials on tank builds: mean damage change 0, remaining-HP change 0, deaths 37 → 37. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "worldroot-girdle":
    "Retain 560: +16 VIT/+12 armor/+5 health recovery strongly improve sustained tank survival and VIT-scaling skills. No maximum-HP increase; repeated mitigation and recovery overlap with endpoint survival. Fresh 128 paired slot trials on tank builds: mean damage change 49.41, remaining-HP change 130.27, deaths 37 → 32. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "bastion-greaves":
    "Retain 310: +8 armor/+6 MR/+1 movement combine protection and access, including offsetting heavy-armor penalties. Slot and movement-only cases support the whole package without pricing the same enabled attack twice. Fresh 256 paired slot trials on agility/tank builds: mean damage change 38.36, remaining-HP change 52.04, deaths 128 → 128. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "gale-striders":
    "Retain 220: +5 AGI/+1 movement can turn a pass into an opening attack. Movement-only trials isolate this tactical gain; close fights do not receive an automatic bonus. Fresh 128 paired slot trials on agility builds: mean damage change 11.57, remaining-HP change 0, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "horizon-walkers":
    "Retain 560: +16 AGI/+2 movement/+10 MR combine mobility with magical protection. Measured approach benefit and mixed-pressure survival support the package; the full avoidance value remains layout-dependent. Fresh 256 paired slot trials on agility/tank builds: mean damage change 61.16, remaining-HP change 38.29, deaths 128 → 128. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "scouts-treads":
    "Retain 160: +5 AGI/+2 armor offer a small numerical improvement over Trailworn. Physical prevention repeats per eligible hit; no mobility premium is assigned. Fresh 256 paired slot trials on agility/tank builds: mean damage change 2.79, remaining-HP change 7.48, deaths 128 → 128. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "tempest-sabatons":
    "Retain 430: +12 AGI/+2 movement support approach and repositioning at longer distance, without defenses. Existing approach cases do not fully distinguish the second movement tile; the remaining reach/avoidance value is a mechanic-based estimate. Fresh 128 paired slot trials on agility builds: mean damage change 24.16, remaining-HP change 0, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "trailworn-boots":
    "Retain the 100-Might boots anchor: +3 AGI, with no extra movement. AGI affects ordering and compatible scaling rather than walking distance. Fresh 128 paired slot trials on agility builds: mean damage change 0, remaining-HP change 0, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "celestial-mantle":
    "Retain 560: +12 INT/+16 MR/+6 mana recovery support prolonged casting under magic pressure. Paired trials show more spent mana and damage; no physical protection is implied. Fresh 256 paired slot trials on caster/tank builds: mean damage change 92.2, remaining-HP change 48.91, deaths 128 → 116. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "mistwoven-cape":
    "Retain 160: +4 INT while retaining +3 MR adds modest caster scaling/recovery over Traveler’s Cloak. Paired output is small in the current rotation, consistent with a conservative numerical upgrade. Fresh 256 paired slot trials on caster/tank builds: mean damage change 3.11, remaining-HP change 0.17, deaths 128 → 128. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "phoenix-shroud":
    "Retain 430: +10 armor/+10 MR/+4 health recovery materially improve mixed-pressure survival. Recovery is useful only while wounded and is not counted twice through end health. Fresh 128 paired slot trials on tank builds: mean damage change 28.56, remaining-HP change 128.03, deaths 32 → 21. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "shadowstalker-cloak":
    "Retain 220: +5 AGI/+4 armor trade magical protection for physical prevention and compatible agility scaling. No automatic dodge or stealth mechanic is implemented. Fresh 256 paired slot trials on agility/tank builds: mean damage change 12.05, remaining-HP change 3.28, deaths 128 → 128. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "spellward-mantle":
    "Retain 310: +8 INT/+8 MR combine caster scaling and magical prevention. Paired gains depend on both using spells and taking magical hits. Fresh 256 paired slot trials on caster/tank builds: mean damage change 26.32, remaining-HP change 18.22, deaths 128 → 128. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "travelers-cloak":
    "Retain the 100-Might cloak anchor: +3 MR protects only against eligible magical hits. Hold the other eight slots fixed. Fresh 128 paired slot trials on tank builds: mean damage change 0, remaining-HP change 0, deaths 32 → 32. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "acolytes-grips":
    "Retain 160: +5 INT/+2 magic penetration improve caster output from gloves. Paired comparisons confirm the role alternative, without treating INT as interchangeable with STR. Fresh 128 paired slot trials on caster builds: mean damage change 30.45, remaining-HP change 0.63, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "brawlers-wraps":
    "Retain the 100-Might gloves anchor: +3 STR improves physical scaling. Hold all other slots fixed. Fresh 128 paired slot trials on physical builds: mean damage change 0, remaining-HP change 0, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "ironbreak-gauntlets":
    "Retain 220: +6 STR/+4 penetration strengthen eligible physical attacks and multi-hit spells. The advantage is larger against armor than unarmored targets. Fresh 128 paired slot trials on physical builds: mean damage change 37.93, remaining-HP change 0.58, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "kingsguard-gauntlets":
    "Retain 560: +16 STR/+8 penetration plus 8% physical lifesteal enable offense to restore missing health. The lifesteal is a useful triggered interaction; current paired healing is credited once and never on overkill or magical damage. Fresh 128 paired slot trials on physical builds: mean damage change 120.85, remaining-HP change 9.07, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "starweave-handwraps":
    "Retain 430: +12 INT/+5 magic penetration materially improve repeated magical hits. Slot trials support caster output; excess mana or fixed-stat totals are not separate power components. Fresh 128 paired slot trials on caster builds: mean damage change 128.66, remaining-HP change 1.69, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "stormgrip-gloves":
    "Retain 310: +8 AGI and six percentage points of crit supply initiative/scaling and critical interactions. Their crit is an implemented source for the reference, not synthetic allowance. Fresh 128 paired slot trials on agility builds: mean damage change 22.77, remaining-HP change 0, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "conquerors-crown":
    "Retain 430: +12 STR/+8 armor combine physical offense and mitigation. Both need eligible actions/hits, and their raw attribute totals do not determine Might. Fresh 256 paired slot trials on physical/tank builds: mean damage change 37.73, remaining-HP change 16.26, deaths 174 → 146. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "dawnwarden-halo":
    "Retain 560: +20 armor/+14 MR/+8 VIT preserve substantial health and enable more actions under mixed pressure. VIT adds recovery, not maximum HP; saturation limits performance against weak enemies. Fresh 128 paired slot trials on tank builds: mean damage change 67.07, remaining-HP change 202.59, deaths 78 → 21. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "iron-cap":
    "Retain the 100-Might helmet anchor: +3 armor prevents up to three physical damage per eligible hit. No MR or health-pool increase. Fresh 128 paired slot trials on tank builds: mean damage change 0, remaining-HP change 0, deaths 78 → 78. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "mossguard-helm":
    "Retain 160: +4 armor/+3 VIT give small repeated mitigation and regeneration gains over Iron Cap. Maximum HP remains fixed; healthy upkeep wastes recovery. Fresh 128 paired slot trials on tank builds: mean damage change 6.05, remaining-HP change 6.78, deaths 78 → 72. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "sentinel-greathelm":
    "Retain 310: +10 armor/+6 MR supply repeated mixed prevention. Current paired trials substantiate preserved health; no offensive or initiative effect is inferred. Fresh 128 paired slot trials on tank builds: mean damage change 22.79, remaining-HP change 74.55, deaths 78 → 32. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "tidekeepers-circlet":
    "Retain 220: +6 INT/+3 MR favor caster output and magical defense. Physical armor is traded away; compatible slot pairs retain that matchup distinction. Fresh 256 paired slot trials on caster/tank builds: mean damage change 31.33, remaining-HP change 0.46, deaths 178 → 178. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "copper-band":
    "Retain the 100-Might ring anchor: +3 STR affects eligible physical attacks/spells. Other slots stay fixed; it is not a universal three-stat exchange rate. Fresh 128 paired slot trials on physical builds: mean damage change 0, remaining-HP change 0, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "duelist-signet":
    "Retain 310: +7 AGI/+6 percentage points of crit interact with agility spells and critical multipliers. Crit works on both damage branches; initiative needs an actual ordering threshold to matter. Fresh 128 paired slot trials on agility builds: mean damage change 21.02, remaining-HP change 0, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "emberseal-ring":
    "Retain 160: +5 STR/+2 penetration improve physical output over Copper Band, especially multi-hit attacks against armor. The paired gain supports the modest step. Fresh 128 paired slot trials on physical builds: mean damage change 18.63, remaining-HP change 0.33, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "sovereign-signet":
    "Retain 560: +12 STR/+12 INT and eight percentage points of crit support hybrid or critical builds. Only scaling actually used by the chosen rotation earns value; the broad stat list is not a second uniqueness premium. Fresh 384 paired slot trials on caster/physical/agility builds: mean damage change 71.77, remaining-HP change 0.44, deaths 288 → 288. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "tidecallers-ring":
    "Retain 220: +7 INT/+1 mana recovery fit a caster in the ring slot. Compare with the slot anchor on the same caster and retain resource-use limits; this is a role alternative, not a STR/INT conversion formula. Fresh 128 paired slot trials on caster builds: mean damage change 60.25, remaining-HP change 0.63, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "wardens-loop":
    "Retain 430: +10 armor/+8 MR preserve health over repeated mixed hits; slot trials confirm survival value. They do not affect one hit simultaneously and can saturate on low damage. Fresh 128 paired slot trials on tank builds: mean damage change 16.45, remaining-HP change 104.8, deaths 32 → 32. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "kingsfall-edge":
    "Retain 560: +24 STR/+12 AGI and 12 percentage points of crit, with 40% STR/15% AGI scaling. Both physical and agile rotations can use the interactions; melee and overkill constrain its substantial offensive package. Fresh 256 paired slot trials on physical/agility builds: mean damage change 147.19, remaining-HP change -6.72, deaths 192 → 192. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "starfall-staff":
    "Retain 430: four-tile magical reach is the defining tactical gain, alongside +20 INT, +8 penetration, +3 mana recovery and stronger 35% INT attacks. Caster slot trials support output; no second reach premium is added to attacks already enabled by range. Fresh 128 paired slot trials on caster builds: mean damage change 267.28, remaining-HP change -6.03, deaths 92 → 92. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
  "sunforged-greatsword":
    "Retain 310: 8–22 base plus 30% STR, +16 STR and +6 penetration improve sustained physical offense. It has no movement or reach addition; the step above Ashen is a numerical upgrade with diminishing useful returns under overkill. Fresh 128 paired slot trials on physical builds: mean damage change 74.41, remaining-HP change -2.14, deaths 96 → 96. Each comparison holds the other eight slots fixed; endpoints are evidence, not an automatic sum or calibrated score.",
} satisfies Record<TieredEquipmentType, string>;
